### ISSUE TITLE
Incorrect URLs in index.yaml

### ISSUE THREAD

**Issue by teebeey** [sonatype-nexus-community/nexus-repository-helm#1]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Download a chart through a Nexus Helm proxy repository. As the path is rewritten incorretly, it gives an error 404.

* **What feature or behavior is this required for?**
Basic functionality.

* **How could we solve this issue? (Not knowing is okay!)**
Updating the `index.yaml` generator to include the path from original index.yaml.  (Alternatively a rewrite rule could be stored in the memory to provide access to the chart on the generated url, but that could cause other issues and harder to implement.)

* **Anything else?**
Original `index.yaml:`
```
    urls:
    - charts/mariadb-3.0.3.tgz
```
`index.yaml` generated by Nexus:
```
    urls:
    - mariadb-3.0.3.tgz
```
So it's missing the `charts/`.

**Comment by DarthHater** [comment]
Interesting! I can solve this for sure, or send a PR if you already got it :)

When I approached writing this I was using the https://kubernetes-charts.storage.googleapis.com/ as my kinda "bible". What repo are you proxying in this case?

**Comment by teebeey** [comment]
Hi, I haven't implemented a fix. Maybe next weekend I could try this, it seems easy, but I haven't looked into the code yet.

I'm using a private helm repository: https://github.com/kubernetes-helm/chartmuseum

**Comment by DarthHater** [comment]
I've got something cooking over on this side, it's in our private repo right now, if the team thinks it solves the issue I'll push it out for you, but definitely send a PR if you come up with something.

When I think about this, we have to handle a few cases:

- index.yaml with relative urls (your issue)
- index.yaml with absolute urls like the one I linked
- index.yaml with absolute urls that have more path to them eg: https://host.com/path/chart.tgz

I've got a potential fix for the first two, and I haven't tested the third yet. Either way, dumping that out of my head in case it helps you :)

**Comment by DarthHater** [comment]
I think I've got the fix for this together. Waiting on a blessing internally and then I'll push it out!

**Comment by springdo** [comment]
hi @DarthHater was this issue resolved in any release of Nexus? Just running into the issue now myself where by the `urls` missing the absolute path. Thanks!
