### ISSUE TITLE
Link to get started guide in README is broken

### ISSUE THREAD

**Issue by OleksandrMykytenko** [sonatype-nexus-community/nexus-repository-helm#117]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I'm trying to get information about usage Nexus as Helm Chart repository
* **What feature or behavior is this required for?**
Readme fix
* **How could we solve this issue? (Not knowing is okay!)**
I suppose check and fix the URL within the text "We have detailed instructions on how to get started here!"
* **Anything else?**

**Comment by mlukaretkyi** [comment]
Will not be relevant. The page will be archived and helm source code will be part of NXRM
