### ISSUE TITLE
Add the support of helm push plugin

### ISSUE THREAD

**Issue by andy812** [sonatype-nexus-community/nexus-repository-helm#124]
I use Nexus Repository Manager OSS 3.21.2. I tried to use hosted helm repo, but can't push chart to it.
I use helm-push plugin (https://github.com/chartmuseum/helm-push), it works with every helm repos i used exept Nexus helm repo.
I got error:
405 HTTP method POST is not supported by this URL

Usage of Nexus API to upload chart (https://github.com/sonatype-nexus-community/nexus-repository-helm/issues/2#issuecomment-569479356) is very inconvenient way in CI/CD pipelines.
Please, add the support of helm push plugin.

**Comment by aornatovskyy** [comment]
Moved to the Jira for further investigation: https://issues.sonatype.org/browse/NEXUS-23331
