### ISSUE TITLE
Support for secondary directory to get helm warehouse

### ISSUE THREAD

**Issue by loverto** [sonatype-nexus-community/nexus-repository-helm#14]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Support for secondary directory to get helm warehouse
* **What feature or behavior is this required for?**
Support for secondary directory to get helm warehouse
* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

helm repo like this

https://burdenbear.github.io/kube-charts-mirror/

![image](https://user-images.githubusercontent.com/3992018/45857062-aa4ad400-bd89-11e8-9d68-2f3cc7b0f060.png)

In this case, there is a problem with the method of setting the relative path before, and the real helm charts will not be obtained.

**Comment by loverto** [comment]
![image](https://user-images.githubusercontent.com/3992018/45857147-031a6c80-bd8a-11e8-9dd9-7f2e2c6324dc.png)

**Comment by DarthHater** [comment]
This is something I did sort of on purpose (I personally didn't know how many repos are out there, so I stuck with just supporting stuff from the root). As I mentioned in #15 , we should break out your changes for this into a separate PR, as I'll need to test this against Proxy and Hosted to ensure it works. Thanks a ton for filing this, and for going the extra mile to make the changes!

**Comment by DarthHater** [comment]
Totally true, GitHub closed this because the original PR mentioned this and the other issue. Reopening!

**Comment by proteus1121** [comment]
@loverto fixed in #81 , will be available in the next helm release.
