### ISSUE TITLE
Programmatically deleting a helm chart from a helm repo in nexus throws a 404 Not found error

### ISSUE THREAD

**Issue by agill17** [sonatype-nexus-community/nexus-repository-helm#22]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Delete a chart from helm repository 

* **What feature or behavior is this required for?**
To perform clean-ups of temporary charts 

* **How could we solve this issue? (Not knowing is okay!)**
By implementing a delete route

* **Anything else?**

**Comment by DarthHater** [comment]
This should be fixed now! You can now `curl -X DELETE` the path of the tar.gz you want to delete. I've released this as 0.0.6

Give it a shot and let me know how it goes for you :) @agill17
