### ISSUE TITLE
Helm hosted repo does not create initial index.yaml file

### ISSUE THREAD

**Issue by ghost** [sonatype-nexus-community/nexus-repository-helm#23]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Add helm hosted repo locally when it's empty.
* **What feature or behavior is this required for?**
When adding empty helm hosted repo, it throw
`index.yaml file not exist` error.
Since there's no charts on the repo, there's no index.yaml file either.
* **How could we solve this issue? (Not knowing is okay!)**
The initial process for helm hosted repo should create an empty index.yaml and don't remove the file even the repo is empty.
* **Anything else?**
N/A

**Comment by DarthHater** [comment]
This is a good idea! It would make adding the repo easier, I imagine. Anyone care to take a run at it?

**Comment by N4rm0** [comment]
@DarthHater Could you please review this PR?

**Comment by petersjtaylor** [comment]
This change seems to cause java.lang.NoSuchMethodError: org.sonatype.nexus.transaction.UnitOfWork.begin(com/google/common/base/Supplier;) when run against 3.20.1.
