### ISSUE TITLE
helm proxy doesn't create index.yaml - 404 Not found

### ISSUE THREAD

**Issue by drbeka** [sonatype-nexus-community/nexus-repository-helm#26]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Have installed nexus-repository-helm plugin 0.0.6 on nexus repository server version 3.13.
Hosted helm repositories are working fine, so I created a proxy helm repository with
name kubernetes-charts, remote URL https://kubernetes-charts.storage.googleapis.com/
and access URL https://mynexus.mycompany.com/repository/kubernetes-charts.
To use that repo I wanted to add the access URL to my helm repo list with:
helm repo add https://mynexus.mycompany.com/repository/kubernetes-charts
but that command failed with:

Error: Looks like "https://mynexus.mycompany.com/repository/kubernetes-charts/" is not a valid chart repository or cannot be reached: Failed to fetch https://mynexus.mycompany.com/repository/kubernetes-charts/index.yaml : 404 Not Found

* **What feature or behavior is this required for?**

We need helm proxy to access public helm chart repositories behind our corporate proxy.

* **How could we solve this issue? (Not knowing is okay!)**

index.yaml should be created during creation of helm proxy repo or it should or the get request for index.yaml should be redirected to the remote URL.

* **Anything else?**

**Comment by drbeka** [comment]
Have installed nexus-repository-helm plugin 0.0.6 on nexus repository server version 3.13.
Hosted helm repositories are working fine, so I created a proxy helm repository with 
name kubernetes-charts, remote URL https://kubernetes-charts.storage.googleapis.com/
and access URL https://mynexus.mycompany.com/repository/kubernetes-charts.
To use that repo I wanted to add the access URL to my helm repo list with:
helm repo add https://mynexus.mycompany.com/repository/kubernetes-charts
but that command failed with:

Error: Looks like "https://mynexus.mycompany.com/repository/kubernetes-charts/" is not a valid chart repository or cannot be reached: Failed to fetch https://mynexus.mycompany.com/repository/kubernetes-charts/index.yaml : 404 Not Found

We need helm proxy to access public helm chart repositories behind our corporate proxy.

index.yaml should be created during creation of helm proxy repo.

**Comment by smackattacka** [comment]
We experience this as well with v0.0.6 on nexus 3.15.2

**Comment by bhamail** [comment]
Fixed by 7c41668
