### ISSUE TITLE
Avoid confusion between plugin version and nexus version

### ISSUE THREAD

**Issue by nicosto** [sonatype-nexus-community/nexus-repository-helm#31]
Hi,

This is a 'feature request'

Having an easy way to match plugin version with nexus version.

I'd like to suggest to bump the plugin version to match the nexus version.

Thanks,
Nicolas

**Comment by paulvi** [comment]
ref #33

That would give false impression about stability of this plugin, IMHO

**Comment by nicosto** [comment]
The issue is to keep track of the relevant version that match the nexus version.
If you load a plugin with the wrong versiont, nexus crash... tested in 3.15.1.
I'd like to prevent this case

**Comment by paulvi** [comment]
oh, I see

but isn't table in README is other way to solve?

https://github.com/sonatype-nexus-community/nexus-repository-helm#compatibility-with-nexus-repository-manager-3-versions

**Comment by bhamail** [comment]
If I understand the concern correctly, I believe the above referenced chart in the README.md makes it clear which version of Nexus should be used. Please reopen/comment if I've missed the point.

**Comment by nicosto** [comment]
Hi,

The main point is the operational use of the plugin with config management
system (ansible).
As Nexus crashs if there is a plugin version mismatch, you have to maintain
a compatibility matrix yourself instead of having a shared variable (the
version).

The readme is useful for the install but not so handy to manage Nexus
upgrade lifecycle.

Cheers
