### ISSUE TITLE
Release 0.0.7 version

### ISSUE THREAD

**Issue by abuzhynsky** [sonatype-nexus-community/nexus-repository-helm#33]
Please release the version 0.0.7 (docs refer to it and looking at the commits seems it's done). Please create the Github release and corresponding git tag. 

We are using the version tags in our CI process building the custom Nexus Docker image with multiple plugins installed. We can use the `master` branch but it's not so convenient.

**Comment by oussemos** [comment]
+1 

ping @DarthHater

**Comment by Chaya56** [comment]
+1

**Comment by dansiviter** [comment]
+1. Adding comment as it seems this project has gone silent.

**Comment by g0blin79** [comment]
+1

**Comment by davidkarlsen** [comment]
This issue seems to have been around for a while - is this project dead?
Also is 0.0.7 compatible with latest 3.16.2-01 release?

**Comment by DarthHater** [comment]
I can take a gander this week. Not dead necessarily, but I paused a bit as
it seems helm was evolving quicker than I could keep up :)

**Comment by cassador** [comment]
@davidkarlsen  the maven build crash when you try to use 3.16.2-01. I already posted an issue about it with corresponding fix as i am trying to implement the 3.16.2-01 with this plugin.

@DarthHater  if you want i can try to contribue from Ops perspective like adjustments which i found required for 3.16.2-01 regarding the pom.xml , Dockerfile etc... Maybe even some optimalization of Dockerfile once i will have a little more time

**Comment by bhamail** [comment]
Since this issue was created, v0.0.8 and v0.0.9 have been release tagged. v0.0.10 is currently on master. Please try using a newer release.
If you really need a "v0.0.7", you might want to try build from this commit: 0626ff3da28631e10cffc5e5180b15505e568dad
