### ISSUE TITLE
Groovy script for creating helm repos ?

### ISSUE THREAD

**Issue by mmaier2** [sonatype-nexus-community/nexus-repository-helm#38]
Hi, 
question: Does the plugin also provides some groovy scripting support? 

* **What are you trying to do?**

Creating a helm repo with support of the scripting API. E.g. something like repository.createPyPiProxy(...)

* **What feature or behavior is this required for?**

Creating a helm repo outside the UI

Thanks
Markus

**Comment by mlukaretkyi** [comment]
Hi. At the moment helm does not support "Groovy script for creating helm repositories". 
So, you need to use NXRM UI
But, coming soon NXRM will have a new REST API.
