### ISSUE TITLE
appVersion not populated in index.yaml

### ISSUE THREAD

**Issue by chrisbsmith** [sonatype-nexus-community/nexus-repository-helm#39]
When performing a `helm search`, the `appVersion` is not returned.  In our case, the `version` and `appVersion` are not the same and we're using `version` to track updates to the Helm chart, and our `appVersion` to specify the version for the deployed software.

* **What are you trying to do?**
View the appVersion from a `helm search`. 

* **What feature or behavior is this required for?**
To specify the `appVersion` in the reults of a helm search

* **How could we solve this issue? (Not knowing is okay!)**
It seems the `appVersion` should be included in the index.yaml 

* **Anything else?**
Here's a quick search and results from our private Nexus repo and my local dev of the chart.

```
> helm search catalog
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
decipher/catalog	1.0.1        	           	A Helm chart to deploy Grey Matter Catalog
local/catalog   	1.0.1        	0.3.6      	A Helm chart to deploy Grey Matter Catalog
```

**Comment by mlukaretkyi** [comment]
Hi, I have looked at your problem and looks like you have worked with a chart that does not have populated appVersion. By the way, I tried to reproduce your problem used MySQL, MongoDB, PostgreSQL and had no success. 
How to make sure. Unzip your chart and inside it find the file called Chart.yaml and this file should have appVersion
