### ISSUE TITLE
Building with latest 3.16.02-01 fails

### ISSUE THREAD

**Issue by cassador** [sonatype-nexus-community/nexus-repository-helm#41]
* **What are you trying to do?**
I tried to build the application with latest nexus which was 3.16.02-01 and the maven build failed on Could not find artifact commons-fileupload:commons-fileupload:jar:1.3.2.SONATYPE

Just adding to pom.xml following dependency worked  (group Id, artifact ID and version)
 <dependency>
    <groupId>commons-fileupload</groupId>
    <artifactId>commons-fileupload</artifactId>
    <version>1.3</version>
</dependency>

I hope this will help also somebody who will strugle the same way as i did :).

**Comment by cassador** [comment]
Also Additional finding was during the build process a change in Dockerfile was required otherwise the container was just crashing. I am also working on implementation of docker-compose to make running this much easier. I think i will run into additional issues during the testing and implementation, but will keep updated this thread with list of changes which were required on my end to run on current latest nexus version

**Comment by bhamail** [comment]
In case it helps, recent patches were applied and built against 3.16.02-01. Specifically, v0.0.9 of the plugin. Please report if using the v0.0.9 version solves the problem. (The latest on master is built against 3.17.0-01).

**Comment by bhamail** [comment]
Closing for now. Please reopen if this is still a problem.
