### ISSUE TITLE
image build error

### ISSUE THREAD

**Issue by wongkafai** [sonatype-nexus-community/nexus-repository-helm#43]
Step 6/15 : RUN cd /nexus-repository-helm/; sed -i "s/3.14.0-04/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml;     mvn clean package;
 ---> Running in a74dc0601fd8
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/nexus/plugins/nexus-plugins/3.14.0-04/nexus-plugins-3.14.0-04.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.sonatype.nexus.plugins:nexus-repository-helm:0.0.7: Could not transfer artifact org.sonatype.nexus.plugins:nexus-plugins:pom:3.14.0-04 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Try again and 'parent.relativePath' points at wrong local POM @ line 19, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.sonatype.nexus.plugins:nexus-repository-helm:0.0.7 (/nexus-repository-helm/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.sonatype.nexus.plugins:nexus-repository-helm:0.0.7: Could not transfer artifact org.sonatype.nexus.plugins:nexus-plugins:pom:3.14.0-04 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Try again and 'parent.relativePath' points at wrong local POM @ line 19, column 11: Unknown host repo.maven.apache.org: Try again -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
The command '/bin/sh -c cd /nexus-repository-helm/; sed -i "s/3.14.0-04/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml;     mvn clean package;' returned a non-zero code: 1

Is there any installation procedure for this repository?

**Comment by bhamail** [comment]
It looks like you are using an old version of the plugin.
Could you try using the latest plugin and let us know if this is still a problem?

**Comment by bhamail** [comment]
Closing for now. Please reopen if this is still a problem.
