### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by tardich** [sonatype-nexus-community/nexus-repository-helm#53]
Trying to build nexus-repository-helm plugin with the setup below, but it doesn't work. Most probably a setup issue but, as I'm not a Java developer, I can't say what's working.

Build environment: Docker container (ubuntu:18.04)
Java installed: default-jdk (openjdk version 11.0.4)
Maven installed: apache-maven-3.6.1-bin.tar.gz
mvn -v:
  Apache Maven 3.6.1
  Maven home: /opt/apache-maven-3.6.1
  Java version: 11.04, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
  OS name: "linux", version: "4.14.122-rancher", arch: "amd64", family: "unix"

I have attached the output of "mvn clean package -l mvn.log"

[mvn.log](https://github.com/sonatype-nexus-community/nexus-repository-helm/files/3542525/mvn.log)

**Comment by bhamail** [comment]
Yes, NXRM requires Java 8. FWIW, upcoming improvements in the 'development' branch will detect and enforce the required Java version, so hopefully this issue will be easier to avoid. Thanks for reporting the problem and your solution!
