### ISSUE TITLE
Getting 504's for manually gzip'd archives with default blocksize (tar)

### ISSUE THREAD

**Issue by gpoirier** [sonatype-nexus-community/nexus-repository-helm#59]
I'm trying to replace `helm package` by manually creating the tgz archives, but when I upload those tgz files to the helm repository in Nexus, I get 504 errors. If I package the exact same chart with the `helm package` command it works.

Both archives works fine when interacting with the `helm` client directly, either for `helm install` or `helm repo index`, both commands work without any problem on the manually created tgz file. It's only when I upload it to Nexus that I have issues.

After lots of investigation, I was able to create an archive that doesn't make Nexus crash without using `helm package`. What made it work was to add the `-b 1` flag to `tar` when creating the archive, setting the blocksize to a smaller value than the default 20, which result in a smaller tar file. For some reason, Nexus didn't crash anymore with that flag. And I also had to only add files explicitly, adding a folder recursively made it crash as well.

**Comment by gpoirier** [comment]
After changing those things mentioned above, the publish was working locally, but it was still failing on Jenkins. I was finally able to make it pass on Jenkins when I changed the order of the files in the tarball to make sure that `Chart.yaml` is first.

**Comment by gpoirier** [comment]
Given what I found about `Chart.yaml`, it seems like skipping the folder entries wasn't really the thing that matter per says, it's likely that when I had the folders included, the root folder was listed before `Chart.yaml` in the tar archive, making the upload processing crash.

**Comment by mlukaretkyi** [comment]
Thanks for your interesting.
Fix was done, and it will be in the next NXRM release.
After release, you can manually create tgz archive and upload it to NXRM.
