### ISSUE TITLE
Nexus Helm Repo : uri not take into account during fetch

### ISSUE THREAD

**Issue by ronny35** [sonatype-nexus-community/nexus-repository-helm#6]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

I try to use one helm repo proxy ( to https://kubernetes-charts.storage.googleapis.com/ ) but I have : 
helm repo add nexusrepo http://nexus/repository/helm-stable-proxy/ 
helm fetch nexusrepo/mongodb
Error: Failed to fetch http://nexus/mongodb-4.3.4.tgz : 404 Not Found

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

Fetch is ok.

* **Anything else?**

**Comment by credit2go** [comment]
by reference note https://github.com/helm/helm/issues/3878, I just try to fix this by changing code. It works fine on my environment with Sonatype Nexus 3.13.01 version

**Comment by loverto** [comment]
[FIX BUG](https://github.com/sonatype-nexus-community/nexus-repository-helm/pull/7)

**Comment by ronny35** [comment]
Thanks, but this issue occurs always with this change.

**Comment by bhamail** [comment]
Is think still a problem with the latest releases? (e.g. v0.0.9+)

**Comment by mlukaretkyi** [comment]
cannot reproduce
